### ISSUE TITLE
use it in a Modal,dialog show ,but under the Modal.it's Covered.

### ISSUE THREAD

**Issue by skynomadism** [jacklam718/react-native-popup-dialog#149]
Use the Modal Component create a view. in the view ,use this dialog,if show it，it's Covered. under the modal.

**Comment by jacklam718** [comment]
A Modal component covers the native view (e.g. UIViewController, Activity) that contains the React Native root.

Use Modal in hybrid apps that embed React Native; Modal allows the portion of your app written in React Native to present content above the enclosing native view hierarchy.

In apps written with React Native from the root view down, you should use Navigator instead of Modal. With a top-level Navigator, you have more control over how to present the modal scene over the rest of your app by using the configureScene property.
